### ISSUE TITLE
建议增加参数

### ISSUE THREAD

**Issue by amu1433** [Merlin218/vitepress-auto-nav-sidebar#3]
1：建议增加参数   设置只遍历搜索 哪个文件名下面的md文档
2:插件左侧列表出现“文章” 这个字可否设置成字段进行修改 ,如果没有设置,则为上级目录名

**Comment by Merlin218** [comment]
> 

1. 意思是只显示部分文件夹中的文章，对吗？是局部控制还是全局控制呢？
2. 字段修改的建议很好，没有设置的话，显示上级目录名是指提供按钮可以返回上一级目录？

**Comment by Merlin218** [comment]
> 1：建议增加参数 设置只遍历搜索 哪个文件名下面的md文档 2:插件左侧列表出现“文章” 这个字可否设置成字段进行修改 ,如果没有设置,则为上级目录名

1. 意思是只显示部分文件夹中的文章，对吗？是局部控制还是全局控制呢？
2. 字段修改的建议很好，没有设置的话，显示上级目录名是指提供按钮可以返回上一级目录？
3. 以上建议可否提供例子参考？

**Comment by amu1433** [comment]
1：全局控制吧...项目里面还有其他文件,比如只搜索 docs文件夹下面的 文件即可
2:比如我的目录是  文档->技术文档->文章1   如果没有设置,则显示 技术文档就行（当前左侧栏目显示的是  文章-文章1等列表...感觉有点怪, 这）
左侧应该是
技术文档
     列表1
     列表2
     列表3

当前问题显示
文章（这个有点怪,最好自定义）
     列表1
     列表2
     列表3

**Comment by Merlin218** [comment]
> 1：全局控制吧...项目里面还有其他文件,比如只搜索 docs文件夹下面的 文件即可 2:比如我的目录是 文档->技术文档->文章1 如果没有设置,则显示 技术文档就行（当前左侧栏目显示的是 文章-文章1等列表...感觉有点怪, 这） 左侧应该是 技术文档 列表1 列表2 列表3
> 
> 当前问题显示 文章（这个有点怪,最好自定义） 列表1 列表2 列表3

- 对于第一点，我多提供了 检索入口的配置项，配合上之前已经有的过滤文件夹的配置项，应该可以满足你的需求？这个问题我之前有考虑过，就是`显示`配置项中的部分，还是`过滤掉`配置项中的部分 之间的选择，我觉得要展示的部分应该是多余隐藏的部分，所以选择了后者。
- 第二点已修复

如果没有问题就发布版本。
